<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <data noupdate="1">

        <!--Email template -->
        <record id="email_template_attendance_device" model="mail.template">
            <field name="name">Attendance Device - Send by Email</field>
            <field name="email_from">System</field>
            <field name="subject">Attendance Device Connection Problem (Ref ${object.name or 'n/a' })</field>
            <field name="partner_to">${object.user_id.id}</field>
            <field name="model_id" ref="to_attendance_device.model_attendance_device"/>
            <field name="lang">${object.user_id.partner_id.lang}</field>
            <field name="auto_delete" eval="True"/>
            <field name="body_html"><![CDATA[
<div style="font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; ">

    <p>Hello ${object.user_id.partner_id.name or ''},</p>
    
    <p>There are some problems with attendance device: ${object.name}. </p>
    
    <p>Please check and troubleshoot.</p>
    
    <p>Best Regard,</p>

</div>
            ]]></field>
        </record>
        
        <record id="email_template_not_safe_to_clear_attendance" model="mail.template">
            <field name="name">Not Safe to clear Attendance Data - Send by Email</field>
            <field name="email_from">System</field>
            <field name="subject">Not Safe to clear Attendance Data (Ref ${object.name})</field>
            <field name="partner_to">${object.user_id.id}</field>
            <field name="model_id" ref="to_attendance_device.model_attendance_device"/>
            <field name="auto_delete" eval="True"/>
            <field name="lang">${object.user_id.partner_id.lang}</field>
            <field name="body_html"><![CDATA[
<div style="font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; ">

    <p>Hello ${object.user_id.partner_id.name or ''},</p>
    
    <p>Odoo tried to delete attendance data from the device ${object.name} but it did not find safe condition to delete since the whole data was not downloaded from the device into Odoo.</p>
    <p>Please also ensure that all the device users have been mapped with Odoo's employees. Otherwise, it is also not safe for attendance data deletion</p>
    <p>Please check and troubleshoot.</p>
    <p>In a case, users are checking in/out while Odoo is downloading data, this message could appear. In such the case, you can ignore this message.</p>
    
    <p>Best Regard,</p>

</div>
            ]]></field>
        </record>
        
        <record id="email_template_error_get_attendance" model="mail.template">
            <field name="name">Error Downloading Attendance Data - Send by Email</field>
            <field name="email_from">System</field>
            <field name="subject">Error Downloading Attendance Data (Ref ${object.name})</field>
            <field name="partner_to">${object.user_id.id}</field>
            <field name="model_id" ref="to_attendance_device.model_attendance_device"/>
            <field name="auto_delete" eval="True"/>
            <field name="lang">${object.user_id.partner_id.lang}</field>
            <field name="body_html"><![CDATA[
<div>
    <p>Hello ${object.user_id.partner_id.name or ''},</p>
    <p>Odoo tried to download attendance data from the device ${object.name} but failed.</p>
    <p>NOTE:</p>
    <p>The device might not return its whole attendance data when requested which could cause this error.</p>
    <p>If such the case, please disconnect the device from Odoo then download the data with another mean from your local network. After that, reconnect the device with Odoo and continue the data synchronization</p>
    <p>Best Regard,</p>
</div>
            ]]></field>
        </record>

    </data>
</odoo>
